server:
  port: 8080
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:18081/uaa/oauth/token
      userAuthorizationUri: http://localhost:18081/uaa/oauth/authorize
      clientId: santander
      clientSecret: santander
    resource:
      userInfoUri: http://localhost:18081/userinfo